image: php:latest
services:
  - postgres:latest
variables:
  POSTGRES_DB: mydb-test
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: "runner"
  POSTGRES_HOST_AUTH_METHOD: trust

before_script:
  - >
    set -xe
    && apt-get update -yqq
    && apt-get install -yqq
    git
    libicu-dev
    libpq-dev
    libzip-dev
    zlib1g-dev
  - >
    docker-php-ext-install
    pdo_pgsql
    pgsql
    sockets
    intl
    zip

phpunit tests:
  stage: test
  script:
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.gitlab-ci .env
    - php artisan key:generate
    - php artisan migrate:fresh --force
    - vendor/bin/phpunit tests
  only:
    - master

deploy to heroku:
  stage: deploy
  script:
    - apt-get install -y ruby
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - master
