image: php:latest
services:
  - postgres:latest
variables:
  POSTGRES_DB: mydb-test
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: "runner"
  POSTGRES_HOST_AUTH_METHOD: trust

before_script:
  - >
    set -xe
    && apt-get update -yqq
    && apt-get install -yqq
    git
    libicu-dev
    libpq-dev
    libzip-dev
    zlib1g-dev
  - >
    docker-php-ext-install
    pdo_pgsql
    pgsql
    sockets
    intl
    zip

composer:
  stage: build
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.gitlab-ci .env
    - php artisan key:generate
    - php artisan migrate:fresh --force
  artifacts:
    expire_in: 1 month
    paths:
      - vendor/
      - .env
  cache:
    paths:
      - vendor/
  only:
    - master

phpunit tests:
  stage: test
  dependencies:
    - composer
  script:
    - vendor/bin/phpunit tests
  only:
    - master

staging:
  stage: deploy
  script:
    - apt-get install -y ruby
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - master
